archetypedir = "archetype"
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
canonifyurls = true
builddrafts = true
googleAnalytics = "UA-74899647-1"
baseurl = "http://ksarmentrout.com"
languageCode = "en-us"
title = "Keaton Armentrout"

[taxonomies]
    category = "categories"
    tag = "tags"

[author]
    name = "Keaton Armentrout"

[params]
    Author = "Keaton Armentrout"
    email = "ksa17@duke.edu"
    DateForm = "Jan 2, 2006"

[[params.social]]
#title = "email"
icon = "envelope-o"
url = "mailto:ksa17@duke.edu"
[[params.social]]
#title = "github"
icon = "github"
url = "https://github.com/ksarmentrout"
[[params.social]]
#title = "linkedin"
icon = "linkedin"
url = "https://www.linkedin.com/in/ksarmentrout"
[[params.social]]
#title = "twitter"
icon = "twitter"
url = "https://twitter.com/keaton_sa"

[[menu.main]]
    name = "home"
    url = "/"
    weight = -200
[[menu.main]]
    name = "Archives"
    url = "/post/"
    weight = -180